add figher and levels and dice pools
Trisfald/srd pull request #15
Opened 2020-08-19 22:13 UTC by Trisfald

Not even a complete Fighter yet, but it's something.

I had to add many stuff: Die and Dices, Proficiency, Levels, etc. Hopefully a small `base` is starting to be born from the mess.

resolves #3 

After this PR we can start to work on actually `spawning` a character.

2020-08-19 22:15 UTC, Trisfald commented on src/character/class/mod.rs
> +        test_case!(1, 2);
perhaps we could wrap the `macro` into a `macro` with ranges .. like `test_cases!(1..=4, 2)`
I have no idea how to do that

2020-08-19 22:16 UTC, Trisfald commented on src/value.rs
> +impl<T: Default + Add + Copy + Ord + Add<T, Output = T>> PositiveBoundedValue<T> {
`rust`'d

2020-08-20 21:02 UTC, LesnyRumcajs requested changes

2020-08-20 21:12 UTC, Trisfald commented on features.md
> +    - [x] 1st Level
it works on my machine

2020-08-20 21:13 UTC, Trisfald commented on src/ability.rs
> +pub const ABILITY_SCORE_MIN: u8 = 1;
I'm not sure. It's kind of private, but maybe the user can use this information? Hm or not.

2020-08-20 21:13 UTC, Trisfald commented on src/ability.rs
>          if value > ABILITY_SCORE_MAX {
almost like a macro

2020-08-20 21:15 UTC, Trisfald commented on src/util.rs
> +    value >= min && value <= max
debug_assert or assert?

2020-08-20 21:16 UTC, LesnyRumcajs commented on src/ability.rs
> +pub const ABILITY_SCORE_MIN: u8 = 1;
I'd say he shouldn't, we should strive to encapsulate what we can. And later with shame accept our fate and decapsulate. :<

2020-08-20 21:20 UTC, LesnyRumcajs commented on src/util.rs
> +    value >= min && value <= max
`assert`. If it occurs, the logic is flawed and there is no point in continuing. If it doesn't, the cost of a simple check is negligible.

2020-08-20 21:21 UTC, Trisfald commented on src/ability.rs
> +pub const ABILITY_SCORE_MIN: u8 = 1;
Haha yes. They can read the manual to know the minimum.

2020-08-20 21:32 UTC, LesnyRumcajs approved these changes

2020-08-20 21:33 UTC, merged